### ISSUE TITLE
Can not read s3:sequence file

### ISSUE THREAD

**Issue by clxy** [greenplum-db/pxf#127]
Version: 5.1.6

We are trying to create an external table to read file on S3.
Here is the data schema class
```java
public class SspUrlDomainAdult implements Writable {

    public String st1 = "";
    public String st2 = "";
    public String st3 = "";

    public SspUrlDomainAdult() {
    }

    public SspUrlDomainAdult(String st1, String st2, String st3) {
        this.st1 = st1;
        this.st2 = st2;
        this.st3 = st3;
    }

    String GetSt1() {
        return st1;
    }

    String GetSt2() {
        return st2;
    }

    String GetSt3() {
        return st3;
    }

    @Override
    public void write(DataOutput out) throws IOException {

        Text txt = new Text();
        txt.set(st1);
        txt.write(out);
        txt.set(st2);
        txt.write(out);
        txt.set(st3);
        txt.write(out);
    }

    @Override
    public void readFields(DataInput in) throws IOException {
        Text txt = new Text();
        txt.readFields(in);
        st1 = txt.toString();
        txt.readFields(in);
        st2 = txt.toString();
        txt.readFields(in);
        st3 = txt.toString();
    }

    public void printFieldTypes() {
        Class myClass = this.getClass();
        Field[] fields = myClass.getDeclaredFields();

        for (int i = 0; i < fields.length; i++) {
            System.out.println(fields[i].getType().getName());
        }
    }
}
```

and the file on S3 is 
- sequence format
- compression type is BLOCK
- compression codec is gzip
- can access by Athena

and the sql of table is
```sql
create external table public.pxf_s3_ssp_url_domain_adult2(
  domain text,
  exclusion_from text,
  exclusion_to text
)
location (
  'pxf://our_bucket/our_table?PROFILE=s3:SequenceFile&DATA-SCHEMA=co.jp.issp.pxf.ssp.SspUrlDomainAdult&SERVER=s3ssp&COMPRESSION_TYPE=BLOCK'
)
format 'CUSTOM' (FORMATTER='pxfwritable_import')
```

This sql can create the table, 
but query is not working on the table.
` select * from pxf_s3_ssp_url_domain_adult2 limit 10; `

Logs are
```
2019-04-03 18:36:53.0702 DEBUG tomcat-http--13 org.greenplum.pxf.api.model.BaseConfigurationFactory - Using directory /usr/local/greenplum-db/pxf/conf/serverss3ssp for server s3ssp configuration
2019-04-03 18:36:53.0703 DEBUG tomcat-http--13 org.greenplum.pxf.api.model.BaseConfigurationFactory - adding configuration resource from file:/usr/local/greenplum-db/pxf/conf/servers/s3ssp/s3-site.xml
2019-04-03 18:36:53.0703 DEBUG tomcat-http--13 org.greenplum.pxf.plugins.hdfs.WritableResolver - Field #0, name: st1 type: java.lang.String, Primitive, accessible field
2019-04-03 18:36:53.0705 DEBUG tomcat-http--13 org.greenplum.pxf.plugins.hdfs.WritableResolver - Field #1, name: st2 type: java.lang.String, Primitive, accessible field
2019-04-03 18:36:53.0705 DEBUG tomcat-http--13 org.greenplum.pxf.plugins.hdfs.WritableResolver - Field #2, name: st3 type: java.lang.String, Primitive, accessible field
2019-04-03 18:36:53.0705 DEBUG tomcat-http--13 org.greenplum.pxf.plugins.hdfs.utilities.HdfsUtilities - No codec was found for file s3a://our_bucket/our_table/000000_0
2019-04-03 18:36:53.0709 DEBUG tomcat-http--13 org.greenplum.pxf.service.bridge.ReadBridge - Bridge is thread safe
2019-04-03 18:36:53.0710 DEBUG tomcat-http--13 org.greenplum.pxf.service.rest.BridgeResource - Request for s3a://our_bucket/our_table/000000_0 will be handled without synchronization
2019-04-03 18:36:53.0711 DEBUG tomcat-http--13 org.greenplum.pxf.api.utilities.Utilities - parsed file split: path s3a://our_bucket/our_table/000000_0, start 0, end 25525, hosts {localhost}
2019-04-03 18:36:53.0816 INFO tomcat-http--13 org.apache.hadoop.io.compress.CodecPool - Got brand-new decompressor [.gz]
2019-04-03 18:36:53.0817 DEBUG tomcat-http--13 org.greenplum.pxf.service.rest.BridgeResource - Starting streaming fragment 0 of resource s3a://our_bucket/our_table/000000_0
2019-04-03 18:36:53.0817 ERROR tomcat-http--13 org.greenplum.pxf.service.rest.BridgeResource - Exception thrown when streaming
java.lang.IllegalArgumentException: Can not set java.lang.String field co.jp.issp.pxf.ssp.SspUrlDomainAdult.st1 to org.apache.hadoop.io.Text
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.greenplum.pxf.plugins.hdfs.WritableResolver.populateRecord(WritableResolver.java:179)
	at org.greenplum.pxf.plugins.hdfs.WritableResolver.getFields(WritableResolver.java:125)
	at org.greenplum.pxf.service.bridge.ReadBridge.makeOutput(ReadBridge.java:76)
	at org.greenplum.pxf.service.bridge.ReadBridge.getNext(ReadBridge.java:106)
	at org.greenplum.pxf.service.rest.BridgeResource$1.write(BridgeResource.java:139)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1437)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.greenplum.pxf.service.servlet.SecurityServletFilter.lambda$doFilter$0(SecurityServletFilter.java:105)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.greenplum.pxf.service.servlet.SecurityServletFilter.doFilter(SecurityServletFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-04-03 18:36:53.0819 DEBUG tomcat-http--13 org.greenplum.pxf.service.rest.BridgeResource - Stopped streaming fragment 0 of resource s3a://our_bucket/our_table/000000_0, 0 records.
2019-04-03 18:36:53.0819 WARN tomcat-http--13 com.amazonaws.services.s3.internal.S3AbortableInputStream - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
2019-04-03 18:36:53.0826 DEBUG tomcat-http--13 org.greenplum.pxf.service.servlet.SecurityServletFilter - Releasing proxy user for session: Session = gpadmin:1554252863-0000048959:1. 

```

Cheers

**Comment by frankgh** [comment]
@clxy Would you be able to share a small sample sequence file, with the same schema, to reproduce the issue on our end?

**Comment by clxy** [comment]
Thank you for answering.

Just for the record, we use those data for exclusion.. ^_^
And, Would you please notice me after downloading.

https://1drv.ms/u/s!AjkmV3h-y3E2j1FCb-ZZhuAgb2bx
password: pxf

Table DDL on Athena
```sql
CREATE EXTERNAL TABLE `url_domain_adult`(
  `domain` string, 
  `exclusion_from` string, 
  `exclusion_to` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY '\t' 
  LINES TERMINATED BY '\n' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.SequenceFileInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat'
LOCATION
  's3://our_bucket/our_table'
```

Thanks again.

**Comment by frankgh** [comment]
Thank you for sharing the information. I have access to the file. Thanks again. 

I will get back to you soon.

**Comment by frankgh** [comment]
@clxy feel free to remove access to the file now

**Comment by clxy** [comment]
Removed!
Thanks!

**Comment by clxy** [comment]
I tried a different way, and make it worked by changing the profile of s3:SequenceFile:
```xml
<!-- $GPHOME/pxf/conf/conf/pxf-profiles.xml -->
  <profile>
    <name>s3:SequenceFile</name>
    ...
    <plugins>
       ...
      <accessor>org.greenplum.pxf.plugins.hdfs.SequenceFileAccessor</accessor>
      <resolver>org.greenplum.pxf.plugins.hdfs.StringPassResolver</resolver>
    </plugins>
    ...
  </profile>
```

and change the sql to
```sql
create external table public.pxf_s3_ssp_url_domain_adult3(
  domain text,
  exclusion_from text,
  exclusion_to text
)
location (
  'pxf://our_bucket/our_table?PROFILE=s3:SequenceFile&DATA-SCHEMA=co.jp.issp.pxf.ssp.SspUrlDomainAdult&SERVER=s3ssp&COMPRESSION_TYPE=BLOCK'
)
FORMAT 'text' (delimiter E'\t' escape '\');
```

As you can see, changing the WritableResolver to StringPassResolver do the trick.

Since we have hundreds of tables, the data-schema definitions drive us crazy.
(Still can't understand the necessity of data-schema on s3:sequence)
So, we probably go this way. I think.

Anyway, let me know if i'm wrong about above or any updated  .

Thanks

**Comment by frankgh** [comment]
Hi @clxy,

I finally got a chance to play with your sample data over the weekend. The solution you gave seems reasonable. However, I would recommend creating your own profile in `$PXF_CONF/conf/pxf-profiles.xml`. Also, you no longer need a custom `DATA-SCHEMA` when using your custom profile.

```xml
    <profile>
        <name>s3:MySequenceProfile</name>
        <plugins>
            <fragmenter>org.greenplum.pxf.plugins.hdfs.HdfsDataFragmenter</fragmenter>
            <accessor>org.greenplum.pxf.plugins.hdfs.SequenceFileAccessor</accessor>
            <resolver>org.greenplum.pxf.plugins.hdfs.StringPassResolver</resolver>
        </plugins>
        <protocol>s3a</protocol>
        <optionMappings>
            <mapping option="accesskey" property="fs.s3a.access.key"/>
            <mapping option="secretkey" property="fs.s3a.secret.key"/>
        </optionMappings>
    </profile>
```

And then using the SQL you provided:

```sql
create external table public.pxf_s3_ssp_url_domain_adult3(
  domain text,
  exclusion_from text,
  exclusion_to text
)
location ( 'pxf://gpdb-ud-scratch/sequence-file/000000_0?PROFILE=s3:SequenceString&SERVER=s3&COMPRESSION_TYPE=BLOCK&COMPRESSION_CODEC=org.apache.hadoop.io.compress.GzipCodec')
format 'text' (delimiter E'\t' escape '\');
```
**Note that you do NOT need to provide `DATA-SCHEMA`.**

Do all your files have the same schema (domain, exclusion_from, exclusion_to)? Or different schemas? 

Let me know if you have any additional questions.
- Francisco

**Comment by clxy** [comment]
@frankgh 
Thank you for answering.

My question is solved, thank you very much.
(Feel free to close this issue. Although, The WritableResolver class still need to fix on this use case, I think.)

> Do all your files have the same schema (domain, exclusion_from, exclusion_to)? Or different schemas?
Yes. our tables(= files on S3) are all different, and have different schamas.

**Comment by frankgh** [comment]
@clxy thanks, we'll take a look into it.
