### ISSUE TITLE
using pxf jdbc writable table insert to db2 lose data

### ISSUE THREAD

**Issue by frankgh** [greenplum-db/pxf#140]
Referenced from GPDB issues: https://github.com/greenplum-db/gpdb/issues/7510

when using pxf and db2 jdbc driver to load millions of data to db2 , mostly the data lost silently，occasionally report following error
2019-04-12 10:17:31.0603 ERROR tomcat-http--17 org.greenplum.pxf.service.rest.WritableResource - Exception: totalWritten so far 59728 to /DB2TMDB.TP_ENTERPRISE/1553735636-0000097227_0
12974 java.io.IOException: Invalid chunk header
12975 at org.apache.coyote.http11.filters.ChunkedInputFilter.throwIOException(ChunkedInputFilter.java:619)
12976 at org.apache.coyote.http11.filters.ChunkedInputFilter.doRead(ChunkedInputFilter.java:192)
12977 at org.apache.coyote.http11.AbstractInputBuffer.doRead(AbstractInputBuffer.java:341)
12978 at org.apache.coyote.Request.doRead(Request.java:431)
12979 at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:290)
12980 at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:390)
12981 at org.apache.catalina.connector.InputBuffer.readByte(InputBuffer.java:304)
12982 at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:106)
12983 at java.io.DataInputStream.readInt(DataInputStream.java:387)
12984 at org.greenplum.pxf.service.io.GPDBWritable.readPktLen(GPDBWritable.java:155)
12985 at org.greenplum.pxf.service.io.GPDBWritable.readFields(GPDBWritable.java:177)
12986 at org.greenplum.pxf.service.BridgeInputBuilder.makeInput(BridgeInputBuilder.java:54)
12987 at org.greenplum.pxf.service.WriteBridge.setNext(WriteBridge.java:74)
12988 at org.greenplum.pxf.service.rest.WritableResource.writeResponse(WritableResource.java:152)
12989 at org.greenplum.pxf.service.rest.WritableResource.stream(WritableResource.java:129)
12990 at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
12991 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
12993 at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
12994 at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
12995 at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
12996 at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
12997 at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
12998 at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
12999 at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
13000 at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
13001 at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
13002 at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
13003 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
13004 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
13005 at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
13006 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
13007 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
13008 at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
13009 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
13010 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
13011 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
13012 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
13013 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
13014 at org.greenplum.pxf.service.servlet.SecurityServletFilter$1.run(SecurityServletFilter.java:99)
13015 at org.greenplum.pxf.service.servlet.SecurityServletFilter$1.run(SecurityServletFilter.java:93)
13016 at java.security.AccessController.doPrivileged(Native Method)
13017 at javax.security.auth.Subject.doAs(Subject.java:422)
13018 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
13019 at org.greenplum.pxf.service.servlet.SecurityServletFilter.doFilter(SecurityServletFilter.java:118)
13020 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
13021 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
13022 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
13023 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
13024 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
13025 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
13026 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
13027 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
13029 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
13030 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
13031 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
13032 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
13033 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13034 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13035 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
13036 at java.lang.Thread.run(Thread.java:748)
13037 2019-04-12 10:38:29.0952 ERROR tomcat-http--7 org.greenplum.pxf.service.rest.BridgeResource - Remote connection closed by GPDB
13038 org.apache.catalina.connector.ClientAbortException: java.net.SocketException: Connection reset
13039 at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:407)
13040 at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
13041 at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:310)
13042 at org.apache.catalina.connector.OutputBuffer.writeByte(OutputBuffer.java:451)
13043 at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:77)
13044 at com.sun.jersey.spi.container.servlet.WebComponent$Writer.write(WebComponent.java:292)
13045 at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:139)
13046 at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
13047 at org.greenplum.pxf.service.io.GPDBWritable.write(GPDBWritable.java:466)
13048 at org.greenplum.pxf.service.rest.BridgeResource$1.write(BridgeResource.java:149)
13049 at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
13050 at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
13051 at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
13052 at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1437)
13053 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
13054 at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
13055 at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
13056 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
13057 at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
13058 at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
13059 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
13060 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
13061 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
13062 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
13063 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

**Comment by frankgh** [comment]
closing for now until we get additional details
