### ISSUE TITLE
pxf+hive+kerberos error

### ISSUE THREAD

**Issue by sydt2014** [greenplum-db/pxf#258]
When pxf connect hive， it occur：
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2019-11-01 20:09:36.0129 WARN tomcat-http--6 hive.metastore - set_ugi() not successful, Likely cause: new client talking to old server. Continuing without it.
org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:380)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_set_ugi(ThriftHiveMetastore.java:3762)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.set_ugi(ThriftHiveMetastore.java:3748)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:502)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:281)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:187)
        at org.greenplum.pxf.plugins.hive.utilities.HiveUtilities.initHiveClient(HiveUtilities.java:94)
        at org.greenplum.pxf.plugins.hive.HiveDataFragmenter.initialize(HiveDataFragmenter.java:113)
        at org.greenplum.pxf.api.utilities.BasePluginFactory.getPlugin(BasePluginFactory.java:54)
        at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.greenplum.pxf.service.servlet.SecurityServletFilter.lambda$doFilter$0(SecurityServletFilter.java:105)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)

but kerberos authorize works:

2019-11-01 20:09:24.0953 INFO localhost-startStop-1 org.greenplum.pxf.service.utilities.SecureLogin - Kerberos Security is enabled
2019-11-01 20:09:24.0954 DEBUG localhost-startStop-1 org.greenplum.pxf.service.utilities.SecureLogin - Kerberos principal: dsarch_gp@DATA.YIRAN.COM
2019-11-01 20:09:24.0954 DEBUG localhost-startStop-1 org.greenplum.pxf.service.utilities.SecureLogin - Kerberos keytab: /home/ansible/dsarch_gp.keytab
2019-11-01 20:09:25.0047 DEBUG localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - hadoop login
2019-11-01 20:09:25.0049 DEBUG localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - hadoop login commit
2019-11-01 20:09:25.0050 DEBUG localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - using kerberos user:dsarch_gp@DATA.YIRAN.COM
2019-11-01 20:09:25.0050 DEBUG localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - Using user: "dsarch_gp@DATA.YIRAN.COM" with name dsarch_gp@DATA.YIRAN.COM
2019-11-01 20:09:25.0051 DEBUG localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - User entry: "dsarch_gp@DATA.YIRAN.COM"
2019-11-01 20:09:25.0051 INFO localhost-startStop-1 org.apache.hadoop.security.UserGroupInformation - Login successful for user dsarch_gp@DATA.YIRAN.COM using keytab file /home/ansible/dsarch_gp.keytab

**Comment by sydt2014** [comment]
bug and repair

**Comment by sydt2014** [comment]
sd
