### ISSUE TITLE
pxf cant not read hadoop federation config

### ISSUE THREAD

**Issue by sydt2014** [greenplum-db/pxf#259]

**Comment by sydt2014** [comment]
2019-11-02 19:02:01.0642 INFO localhost-startStop-1 org.greenplum.pxf.service.utilities.Log4jConfigure - Initialized logging: log4jConfigLocation = /home/ansible/pxf6/conf/conf/pxf-log4j.properties
2019-11-02 19:02:01.0642 INFO localhost-startStop-1 javax.servlet.ServletContextListener - PXF server webapp initialized
2019-11-02 19:02:01.0647 INFO localhost-startStop-1 org.greenplum.pxf.service.utilities.SecureLogin - User impersonation is disabled
2019-11-02 19:02:01.0802 ERROR localhost-startStop-1 org.apache.hadoop.conf.Configuration - error parsing conf file:/home/ansible/pxf6/conf/servers/default/core-site.xml
java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/home/ansible/pxf6/conf/servers/default/core-site.xml'
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2916)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2730)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2605)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1269)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1241)
        at org.greenplum.pxf.api.model.BaseConfigurationFactory.processServerResources(BaseConfigurationFactory.java:97)
        at org.greenplum.pxf.api.model.BaseConfigurationFactory.initConfiguration(BaseConfigurationFactory.java:72)
        at org.greenplum.pxf.service.utilities.SecureLogin.login(SecureLogin.java:73)
        at org.greenplum.pxf.service.servlet.ServletLifecycleListener.contextInitialized(ServletLifecycleListener.java:52)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-11-02 19:02:01.0804 ERROR localhost-startStop-1 org.greenplum.pxf.service.utilities.SecureLogin - PXF service login failed: Unable to read configuration for server default from /home/ansible/pxf6/conf/servers/default
2019-11-02 19:02:01.0809 INFO localhost-startStop-1 javax.servlet.ServletContextListener - PXF server webapp is about to go down
~

**Comment by eralper** [comment]
Hello @sydt2014 ,
Could you solve this issue? What was the problem? I have a similar case...

**Comment by oliverralbertini** [comment]
>error parsing conf file:/home/ansible/pxf6/conf/servers/default/core-site.xml

Looks like there was something wrong with the XML in `$PXF_CONF/conf/servers/default/core-site.xml`. If this is the error you are seeing, you probably need to fix an issue with your XML.
