### ISSUE TITLE
com.google.protobuf.ServiceException: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to node1/192.168.18.1:46049 failed on local

### ISSUE THREAD

**Issue by fuhao009** [greenplum-db/pxf#289]
gp6.2.1 through pxf import hbase data to 
environment：
hadoop-2.6.5.
hbase-1.2.7
error message:
Jan 14, 2020 4:05:56 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
org.apache.hadoop.hbase.MasterNotRunningException: com.google.protobuf.ServiceException: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Call to node1/192.168.18.1:46049 failed on local exception: org.apache.hadoop.hbase.exceptions.ConnectionClosingException: Connection to node1/192.168.18.1:46049 is closing. Call id=0, waitTime=52
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation$StubMaker.makeStub(ConnectionManager.java:1573)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(ConnectionManager.java:1593)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getKeepAliveMasterService(ConnectionManager.java:1750)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.isMasterRunning(ConnectionManager.java:955)
        at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:3181)
        at org.greenplum.pxf.plugins.hbase.HBaseDataFragmenter.getFragments(HBaseDataFragmenter.java:89)
        at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:186)
        at org.greenplum.pxf.service.rest.FragmenterResource.access$100(FragmenterResource.java:62)
        at org.greenplum.pxf.service.rest.FragmenterResource$1.call(FragmenterResource.java:128)
        at org.greenplum.pxf.service.rest.FragmenterResource$1.call(FragmenterResource.java:122)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
        at org.greenplum.pxf.service.rest.FragmenterResource.getFragments(FragmenterResource.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

**Comment by yydzero** [comment]
@vraghavan78  Would be great if you could take a look at this? Thanks!

**Comment by frankgh** [comment]
@fuhao009 can you confirm that you have performed the prerequisite steps mentioned here:

https://gpdb.docs.pivotal.io/6-2/pxf/hbase_pxf.html

> - Copied $GPHOME/pxf/lib/pxf-hbase-*.jar to each node in your HBase cluster, and that the location of this PXF JAR file is in the $HBASE_CLASSPATH. This configuration is required for the PXF HBase connector to support filter pushdown.
> - Met the PXF Hadoop Prerequisites.

**Comment by frankgh** [comment]
@fuhao009 also, can you provide DDL for your external table in Greenplum and definition for your HBase table?

**Comment by denalex** [comment]
Is HBase master running on node1/192.168.18.1 ? Any errors in Hbase master log ?

**Comment by fuhao009** [comment]
no,Hbase belongs to a separate node，ddl：
create 'order_info', 'product', 'shipping_info'

put 'order_info', '1', 'product:name', 'tennis racquet'
put 'order_info', '1', 'product:location', 'out of stock'
put 'order_info', '1', 'shipping_info:state', 'CA'
put 'order_info', '1', 'shipping_info:zipcode', '12345'
put 'order_info', '2', 'product:name', 'soccer ball'
put 'order_info', '2', 'product:location', 'on floor'
put 'order_info', '2', 'shipping_info:state', 'CO'
put 'order_info', '2', 'shipping_info:zipcode', '56789'
put 'order_info', '3', 'product:name', 'snorkel set'
put 'order_info', '3', 'product:location', 'warehouse'
put 'order_info', '3', 'shipping_info:state', 'OH'
put 'order_info', '3', 'shipping_info:zipcode', '34567'

**Comment by denalex** [comment]
It seems from the logs that HBase client tries to connect to that node: `Call to node1/192.168.18.1:46049 failed on local exception`. Can you please provide the content of your `hbase-site.xml` file from the PXF server configuration directory ?

**Comment by fuhao009** [comment]
[gpadmin@mdw default]$ cat hbase.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property>
        <name>hbase.rootdir</name>
        <value>hdfs://node1:9000/hbase</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>node1</value>
    </property>
</configuration>
[gpadmin@mdw default]$

**Comment by fuhao009** [comment]
[gpadmin@mdw default]$ cat /etc/hosts
127.0.0.1	localhost	localhost.localdomain	localhost4	localhost4.localdomain4
::1	localhost	localhost.localdomain	localhost6	localhost6.localdomain6
192.168.18.50	sdw1
192.168.18.51	sdw2
192.168.18.49	mdw
192.168.18.1 node1

**Comment by fuhao009** [comment]
[gpadmin@mdw default]$ cat hbase.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property>
        <name>hbase.rootdir</name>
        <value>hdfs://node1:9000/hbase</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>node1</value>
    </property>
</configuration>
[gpadmin@mdw default]$

**Comment by fuhao009** [comment]
<configuration>
    <property>
        <name>hbase.rootdir</name>
        <value>hdfs://node1:9000/hbase</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>node1</value>
    </property>

**Comment by fuhao009** [comment]
<property>
        <name>hbase.rootdir</name>
        <value>hdfs://node1:9000/hbase</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>node1</value>
    </property>

**Comment by fuhao009** [comment]
greenplum6.2.1 or greenplum6.3 
Does hbase need to be installed on every segment node?

**Comment by frankgh** [comment]
@fuhao009 HBase does not need to be installed on the greenplum cluster. can you make sure your `/etc/hosts` for every segment host has the node1 entry. Is the IP address `192.168.18.1` where your HBase master is running?

**Comment by fuhao009** [comment]
I want to implement greenplum external table access hive, hive external table access es, is that feasible?
greenplum:6.2.1 -> hive:1.2.2 -> es:6.5.4
es:6.5.4
hive:1.2.2
PUT test01 
{
  "settings": {
    "number_of_shards": 5
    , "number_of_replicas": 1
  }
}

PUT test01/_doc/_mapping
{
  "properties": {
    "id":{
      "type": "keyword"
    },
    "name":{
      "type": "keyword"
    }
  }
}
CREATE EXTERNAL TABLE test01(
   idcard string,
   fid string
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource'='test01/_doc',
'es.nodes'='http://192.168.18.240:9200/',
'es.port'='9200',
'es.index.auto.create'='TRUE'
);
greenplum 6.2.1
CREATE EXTERNAL TABLE test01(idcard text,fid text)
            LOCATION ('pxf://default.test01?PROFILE=Hive')
          FORMAT 'custom' (FORMATTER='pxfwritable_import');
err_message:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [XX000]: ERROR: remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   java.lang.NullPointerException (libchurl.c:920)  (seg3 slice1 192.168.18.51:33001 pid=3735) (libchurl.c:920)
  在位置：External table elastic_bank_2
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:481)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:420)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:412)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:771)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2859)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:154)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3434)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: remote component error (500) from '127.0.0.1:5888':  Type  Exception Report   Description  The server encountered an unexpected condition that prevented it from fulfilling the request.   Exception   java.lang.NullPointerException (libchurl.c:920)  (seg3 slice1 192.168.18.51:33001 pid=3735) (libchurl.c:920)
  在位置：External table elastic_bank_2
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**Comment by fuhao009** [comment]
@yydzero hi？

**Comment by yydzero** [comment]
@fuhao009 could you please help to answer @frankgh 's question, think it is more valuable to solve this issue.  It is possible to add ES, while that is another question.

**Comment by frankgh** [comment]
@fuhao009 were you able to fix this issue?

**Comment by frankgh** [comment]
@fuhao009 we are closing this issue for now. Feel free to reopen if you still face the same issue
