### ISSUE TITLE
Pxf error when selecting from hive and inserting into gpdb

### ISSUE THREAD

**Issue by zlokomatic** [greenplum-db/pxf#968]
GPDB Version: 6.22.1
Pxf Version:  6.4.2
Server: Ubuntu 18.04.6

Hi,

i get an error when im inserting into out gpdb Database with data selected from hive via pxf.

```
2023-04-19 07:17:41.479 UTC  INFO [1681473101-0000122470:default:18 ] 29529 --- [response-4] o.g.p.s.c.BaseServiceImpl                : Aborted read operation [321936 ms, 102177 records, 317.38 records/sec, 46383088 bytes, 144075.49 bytes/sec] for hdfs://dwh/user/hive/history/mail_data/partitioned/year=2023/month=1/day=1/000012_0
2023-04-19 07:17:41.478 UTC  WARN [1681473101-0000122470:default:9  ] 29529 --- [response-2] o.g.p.s.c.PxfErrorReporter               : Remote connection closed by the client.

org.apache.catalina.connector.ClientAbortException: java.net.SocketTimeoutException
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:783) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:688) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:366) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96) ~[tomcat-embed-core-9.0.60.jar!/:?]
        at com.google.common.io.CountingOutputStream.write(CountingOutputStream.java:53) ~[guava-20.0.jar!/:?]
        at java.io.DataOutputStream.write(DataOutputStream.java:107) ~[?:1.8.0_362]
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97) ~[?:1.8.0_362]
        at org.greenplum.pxf.api.io.GPDBWritable.write(GPDBWritable.java:475) ~[pxf-api-6.4.2.jar!/:?]
        at org.greenplum.pxf.service.controller.ReadServiceImpl.processFragment(ReadServiceImpl.java:158) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.ReadServiceImpl.writeStream(ReadServiceImpl.java:101) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.ReadServiceImpl.lambda$null$0(ReadServiceImpl.java:58) ~[classes!/:6.4.2]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_362]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1918) ~[hadoop-common-2.10.2.jar!/:?]
        at org.greenplum.pxf.service.security.BaseSecurityService.doAs(BaseSecurityService.java:122) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.BaseServiceImpl.processData(BaseServiceImpl.java:74) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.ReadServiceImpl.lambda$readData$1(ReadServiceImpl.java:58) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.PxfErrorReporter.invokeWithErrorHandling(PxfErrorReporter.java:26) ~[classes!/:6.4.2]
        at org.greenplum.pxf.service.controller.ReadServiceImpl.readData(ReadServiceImpl.java:58) ~[classes!/:6.4.2]
```

        
In the hive and hdfs logs i can not see anything. In gpdb i only get the error:

`[2023-04-19 09:23:07] [XX000] ERROR: transfer error (56): Failure when receiving data from the peer from '127.0.0.1:5888' (libchurl.c:929)  (seg15 slice1 172.16.26.154:6003 pid=16859) (libchurl.c:929)`

What can i do to debug any further?

Kind Regards,

David

**Comment by zlokomatic** [comment]
Looks like this was the Problem.
I had another Problem with timeouts that i could fix by changing the interconnect type to tcp.

Thanks for your help :)

**Comment by zlokomatic** [comment]
I'm sorry to reopen this issue but now i got another error message when running the same queries:

ERROR:  transfer error (18): Transferred a partial file from '127.0.0.1:5888' (libchurl.c:930)  (seg1 slice1 data01:6001 pid=14881) (libchurl.c:930)
DETAIL:  curl error buffer: transfer closed with outstanding read data remaining
CONTEXT:  External table ext_mail_data_2023
